<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<HTML>
 <HEAD>
   <TITLE> [HarvestMan-devel] Harvestman install problem
   </TITLE>
   <LINK REL="Index" HREF="http://lists.berlios.de/pipermail/harvestman-devel/2008-July/index.html" >
   <LINK REL="made" HREF="mailto:harvestman-devel%40lists.berlios.de?Subject=Re%3A%20%5BHarvestMan-devel%5D%20Harvestman%20install%20problem&In-Reply-To=%3Cc9952a990807100546o3a9023e4raa4e5c2b5d1fcc3f%40mail.gmail.com%3E">
   <META NAME="robots" CONTENT="index,nofollow">
   <style type="text/css">
       pre {
           white-space: pre-wrap;       /* css-2.1, curent FF, Opera, Safari */
           }
   </style>
   <META http-equiv="Content-Type" content="text/html; charset=us-ascii">
   <LINK REL="Previous"  HREF="000101.html">
   <LINK REL="Next"  HREF="000103.html">
 </HEAD>
 <BODY BGCOLOR="#ffffff">
   <H1>[HarvestMan-devel] Harvestman install problem</H1>
    <B>wenjie zheng</B> 
    <A HREF="mailto:harvestman-devel%40lists.berlios.de?Subject=Re%3A%20%5BHarvestMan-devel%5D%20Harvestman%20install%20problem&In-Reply-To=%3Cc9952a990807100546o3a9023e4raa4e5c2b5d1fcc3f%40mail.gmail.com%3E"
       TITLE="[HarvestMan-devel] Harvestman install problem">wenjie.zheng at gmail.com
       </A><BR>
    <I>Thu Jul 10 14:46:33 CEST 2008</I>
    <P><UL>
        <LI>Previous message: <A HREF="000101.html">[HarvestMan-devel] Harvestman install problem
</A></li>
        <LI>Next message: <A HREF="000103.html">[HarvestMan-devel] Harvestman install problem
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#102">[ date ]</a>
              <a href="thread.html#102">[ thread ]</a>
              <a href="subject.html#102">[ subject ]</a>
              <a href="author.html#102">[ author ]</a>
         </LI>
       </UL>
    <HR>  
<!--beginarticle-->
<PRE>Thanks.

After doing svn up, another error popped up.

Traceback (most recent call last):
  File &quot;setup.py&quot;, line 463, in ?
    main()
  File &quot;setup.py&quot;, line 435, in main
    from harvestman.test import run_tests
  File &quot;/home/wzheng/code/HarvestMan-2.0/harvestman/test/run_tests.py&quot;,
line 10, in ?
    import test_connector
  File &quot;/home/wzheng/code/HarvestMan-2.0/harvestman/test/test_connector.py&quot;,
line 14, in ?
    test_base.setUp()
  File &quot;/home/wzheng/code/HarvestMan-2.0/harvestman/test/test_base.py&quot;,
line 34, in setUp
    from lib import datamgr
  File &quot;/home/wzheng/code/HarvestMan-2.0/harvestman/lib/datamgr.py&quot;,
line 57, in ?
    from mirrors import HarvestManMirrorManager
  File &quot;/home/wzheng/code/HarvestMan-2.0/harvestman/lib/mirrors.py&quot;,
line 135, in ?
    class HarvestManMirrorSearch(object):
  File &quot;/home/wzheng/code/HarvestMan-2.0/harvestman/lib/mirrors.py&quot;,
line 144, in HarvestManMirrorSearch
    quotes_re = re.compile(r'[\'\&quot;]')
NameError: name 're' is not defined

It can be fixed by adding &quot;import re&quot;.

However, after installation successfully finished, 1 unit test failed.

Fresh installation, running unit tests...
Running test_connector...
test_connect...
test_connect_etag...
test_connect_lmt...
Running test_urlparser...
Ran 10 tests, 9 passes, 1 failures
Creating application links...
Creating application link for harvestman...
Creating application link for hget...

Do you know where I can find out which unit test failed and where the log is?

Thanks,
Wenjie

On Thu, Jul 10, 2008 at 4:50 AM, Anand Balachandran Pillai
&lt;<A HREF="https://lists.berlios.de/mailman/listinfo/harvestman-devel">abpillai at gmail.com</A>&gt; wrote:
&gt;<i> Thanks, fixed this. Update your svn and it will install.
</I>&gt;<i>
</I>&gt;<i> Hereafter please CC &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/harvestman-devel">harvestman-devel at lists.berlios.de</A>&gt; also in your emails
</I>&gt;<i> regarding HarvestMan.
</I>&gt;<i>
</I>&gt;<i> Thanks
</I>&gt;<i>
</I>&gt;<i> --Anand
</I>&gt;<i>
</I>&gt;<i> On Thu, Jul 10, 2008 at 2:46 AM, wenjie zheng &lt;<A HREF="https://lists.berlios.de/mailman/listinfo/harvestman-devel">wenjie.zheng at gmail.com</A>&gt; wrote:
</I>&gt;&gt;<i> Hi Anand,
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I encountered a problem when I tried to install the latest version
</I>&gt;&gt;<i> Harvestman (svn co ...)
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> It got stuck when trying to creating config file
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> ...
</I>&gt;&gt;<i> Creating basic configuration in /etc/harvestman...
</I>&gt;&gt;<i> Traceback (most recent call last):
</I>&gt;&gt;<i>  File &quot;setup.py&quot;, line 463, in ?
</I>&gt;&gt;<i>    main()
</I>&gt;&gt;<i>  File &quot;setup.py&quot;, line 406, in main
</I>&gt;&gt;<i>    conf_data = cfg.generate_system_configuration()
</I>&gt;&gt;<i>  File &quot;/home/wzheng/code/HarvestMan-2.0/harvestman/lib/config.py&quot;,
</I>&gt;&gt;<i> line 1526, in generate_system_configuration
</I>&gt;&gt;<i>    return CONFIG_XML_TEMPLATE % self
</I>&gt;&gt;<i> KeyError: 'USERAGENT'
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> I am using Python 2.4.3 on a CentOS box with 2.6 kernel.
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Thanks a bunch!
</I>&gt;&gt;<i>
</I>&gt;&gt;<i> Wenjie
</I>&gt;&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i>
</I>&gt;<i> --
</I>&gt;<i> -Anand
</I>&gt;<i>
</I>
</PRE>

<!--endarticle-->
    <HR>
    <P><UL>
        <!--threads-->
	<LI>Previous message: <A HREF="000101.html">[HarvestMan-devel] Harvestman install problem
</A></li>
	<LI>Next message: <A HREF="000103.html">[HarvestMan-devel] Harvestman install problem
</A></li>
         <LI> <B>Messages sorted by:</B> 
              <a href="date.html#102">[ date ]</a>
              <a href="thread.html#102">[ thread ]</a>
              <a href="subject.html#102">[ subject ]</a>
              <a href="author.html#102">[ author ]</a>
         </LI>
       </UL>

<hr>
<a href="https://lists.berlios.de/mailman/listinfo/harvestman-devel">More information about the HarvestMan-devel
mailing list</a><br>
</body></html>
